# FILE: docker-compose.yml
services:
  backend:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      DATABASE_URL: "postgresql://pe#sFFwKZLM1Xz:pe#sFFwKZLM1Xz@celestia-art-db.cbm268a4go9m.eu-central-1.rds.amazonaws.com:5432/celestia-art-db"
      S3_BUCKET_NAME: "celestia-ms-101"
      AWS_REGION: "eu-central-1"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      AI_INSTANCE_LAUNCH_TEMPLATE: "celestia-ai-template"

    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - celestia
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - celestia

networks:
  celestia:
    driver: bridge

volumes:
  redis_data: