# FILE: docker-compose.yml
services:
  backend:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - celestia
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - celestia

networks:
  celestia:
    driver: bridge

volumes:
  redis_data: